apiVersion: v1
kind: ReplicationController
metadata:
  name: server
spec:
  replicas: 4
  selector:
    role: server
  template:
    metadata:
      labels:
        role: server
    spec:
      containers:
      - name: server
        image: nginx
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: cinderpvc
      volumes:
        - name: cinderpvc
          persistentVolumeClaim:
            claimName: claim1
